# Generated by Django 3.2.8 on 2023-11-12 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vet', '0031_alter_appointment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.PositiveIntegerField()),
                ('communication', models.PositiveIntegerField()),
                ('professionalism', models.PositiveIntegerField()),
                ('equipment', models.PositiveIntegerField()),
                ('service', models.PositiveIntegerField()),
                ('transparency', models.PositiveIntegerField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='vet.appointment')),
            ],
        ),
    ]
