# Generated by Django 3.2.8 on 2023-11-12 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0032_auto_20231111_2358'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='appointment',
        ),
        migrations.AddField(
            model_name='rating',
            name='record',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='vet.medicalrecord'),
            preserve_default=False,
        ),
    ]
