# Generated by Django 3.2.8 on 2023-11-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0033_medicalrecord_r_rating'),
        ('rating', '0002_auto_20231111_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='vet.medicalrecord'),
        ),
    ]
