# Generated by Django 3.2.8 on 2023-08-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doggy', '0002_alter_vet_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('vaccines', models.CharField(max_length=30)),
            ],
        ),
    ]
