# Generated by Django 3.2.8 on 2023-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doggy', '0003_dog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(default=0, upload_to='Doggy/images/'),
            preserve_default=False,
        ),
    ]
