# Generated by Django 4.2.4 on 2023-10-12 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinic_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('opening_hours', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('vet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vet')),
            ],
        ),
    ]
