# Generated by Django 3.2.8 on 2023-10-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='speciality',
        ),
        migrations.AddField(
            model_name='vet',
            name='specialty',
            field=models.CharField(choices=[('General Medicine', 'General Medicine'), ('Surgery', 'Surgery'), ('Dermatology', 'Dermatology'), ('Ophthalmology', 'Ophthalmology'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Dentistry', 'Dentistry'), ('Orthopedics', 'Orthopedics'), ('Internal Medicine', 'Internal Medicine'), ('Oncology', 'Oncology'), ('Rehabilitation and Physical Therapy', 'Rehabilitation and Physical Therapy'), ('Animal Behavior', 'Animal Behavior'), ('Emergency and Critical Care Medicine', 'Emergency and Critical Care Medicine'), ('Radiology and Diagnostic Imaging', 'Radiology and Diagnostic Imaging'), ('Preventive Medicine', 'Preventive Medicine'), ('Holistic Medicine', 'Holistic Medicine')], default='General Medicine', max_length=100),
            preserve_default=False,
        ),
    ]
