# Generated by Django 4.2.4 on 2023-10-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_vet_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('duration', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('aviability', models.BooleanField(default=False)),
                ('clinic_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.clinic_info')),
            ],
        ),
    ]
