# Generated by Django 4.2.4 on 2023-10-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_treatment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic_info',
            options={'permissions': [('can_manage_clinic', 'Can manage clinic')]},
        ),
    ]
