# Generated by Django 4.2.4 on 2023-10-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_clinic_info_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinic_info',
            options={},
        ),
    ]
