# Generated by Django 4.2.4 on 2023-10-14 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20231011_1643'),
        ('accounts', '0006_alter_clinic_info_options'),
    ]

    operations = [
    ]
