# Generated by Django 4.2.4 on 2023-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_clinic_info_description_alter_owner_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic_info',
            name='place',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
