# Generated by Django 4.2.4 on 2023-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clinic_info_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_info',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
