# Generated by Django 4.2.4 on 2023-10-15 23:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_clinic_info_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='telephone',
            field=models.CharField(max_length=50, validators=[accounts.models.validate_numeric]),
        ),
        migrations.AlterField(
            model_name='vet',
            name='telephone',
            field=models.CharField(max_length=50, validators=[accounts.models.validate_numeric]),
        ),
    ]
