# Generated by Django 3.2.8 on 2023-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_vet_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic_info',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
