# Generated by Django 3.2.8 on 2023-08-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('image', models.ImageField(upload_to='images/')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('breed', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('vaccines', models.CharField(max_length=30)),
            ],
        ),
    ]
