# Generated by Django 4.2.4 on 2023-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointmentType', models.CharField(max_length=100)),
                ('symptoms', models.CharField(max_length=100)),
                ('treatment', models.CharField(max_length=100)),
                ('recomendations', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
