# Generated by Django 4.2.4 on 2023-09-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0003_medicalrecord_dog'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccination_card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rabies', models.BooleanField(default=False, verbose_name='Rabies')),
                ('CanineDistemper', models.BooleanField(default=False, verbose_name='Canine Distemper')),
                ('Parvovirus', models.BooleanField(default=False, verbose_name='Parvovirus')),
                ('Adenovirus', models.BooleanField(default=False, verbose_name='Adenovirus(CAV-1)')),
                ('Adenovirus_2', models.BooleanField(default=False, verbose_name='Adenovirus(CAV-2)')),
                ('Parainfluenza', models.BooleanField(default=False, verbose_name='Parainfluenza')),
                ('Bordetella', models.BooleanField(default=False, verbose_name='Bordetella')),
                ('LymeDisease', models.BooleanField(default=False, verbose_name='Lyme Disease')),
                ('CanineInfluenza', models.BooleanField(default=False, verbose_name='Canine Influenza')),
                ('dogID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.dog')),
            ],
        ),
    ]
