# Generated by Django 4.2.4 on 2023-09-08 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0004_vaccination_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination_card',
            name='dogID',
        ),
        migrations.AddField(
            model_name='dog',
            name='vaccination_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.vaccination_card'),
        ),
    ]
