# Generated by Django 3.2.8 on 2023-09-09 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0005_remove_vaccination_card_dogid_dog_vaccination_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='vaccines',
        ),
    ]
