# Generated by Django 4.2.4 on 2023-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0006_remove_dog_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='id',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='record_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
