# Generated by Django 4.2.4 on 2023-09-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0008_rename_record_id_medicalrecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
