# Generated by Django 4.2.4 on 2023-09-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0010_rename_recomendations_medicalrecord_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
