# Generated by Django 4.2.4 on 2023-09-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0013_alter_medicalrecord_recommendations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('appointment_type', models.CharField(max_length=20)),
                ('dog_owner_name', models.CharField(max_length=50)),
                ('vet_name', models.CharField(max_length=50)),
                ('clinic_address', models.CharField(max_length=50)),
            ],
        ),
    ]
