# Generated by Django 4.2.4 on 2023-09-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0015_rename_clinic_address_appointment_clinic_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dog_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.dog'),
        ),
    ]
