# Generated by Django 4.2.4 on 2023-09-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0016_appointment_dog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.CharField(max_length=500),
        ),
    ]
