# Generated by Django 3.2.8 on 2023-10-05 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('vet', '0019_alter_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vet'),
        ),
    ]
