# Generated by Django 3.2.8 on 2023-10-05 15:53

from django.db import migrations, models
import django.db.models.deletion
import vet.models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0020_dog_vet'),
    ]

    operations = [
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('max_size', models.IntegerField()),
                ('life_expectancy', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthdate',
            field=models.DateField(validators=[vet.models.validate_minor]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vet.breed'),
        ),
    ]
