# Generated by Django 3.2.8 on 2023-10-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0021_auto_20231005_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='life_expectancy',
        ),
        migrations.RemoveField(
            model_name='breed',
            name='max_size',
        ),
    ]
