# Generated by Django 4.2.4 on 2023-10-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0022_auto_20231005_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='recommendations',
            field=models.CharField(max_length=1000),
        ),
    ]
