# Generated by Django 4.2.4 on 2023-10-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_clinic_info_description_alter_owner_birthdate_and_more'),
        ('vet', '0023_alter_medicalrecord_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='vet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.vet'),
            preserve_default=False,
        ),
    ]
