# Generated by Django 4.2.4 on 2023-10-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0025_alter_dog_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='treatment',
            new_name='procedure',
        ),
    ]
