# Generated by Django 4.2.4 on 2023-10-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0026_rename_treatment_medicalrecord_procedure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='procedure',
            new_name='treatment',
        ),
    ]
