# Generated by Django 3.2.8 on 2023-10-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0028_auto_20231015_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
