# Generated by Django 4.2.4 on 2023-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0030_rename_dog_id_appointment_dog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(max_length=100),
        ),
    ]
