# Generated by Django 4.2.4 on 2023-11-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0031_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Attended'),
        ),
    ]
