# Generated by Django 3.2.8 on 2023-11-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0032_auto_20231111_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='r_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
