# Generated by Django 3.2.8 on 2023-11-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0033_medicalrecord_r_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='r_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
