# Generated by Django 4.2.4 on 2023-11-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0034_alter_medicalrecord_r_rating'),
        ('vet', '0034_news'),
    ]

    operations = [
    ]
