# Generated by Django 4.2.4 on 2023-11-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0035_merge_0034_alter_medicalrecord_r_rating_0034_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='attended',
            new_name='is_attended',
        ),
    ]
