# Generated by Django 4.2.4 on 2023-11-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0036_rename_attended_appointment_is_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='is_attended',
            new_name='attended',
        ),
    ]
