# Generated by Django 4.2.4 on 2023-11-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vet', '0037_rename_is_attended_appointment_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination_card',
            name='Adenovirus',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='Adenovirus_2',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='Bordetella',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='CanineDistemper',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='CanineInfluenza',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='LymeDisease',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='Parainfluenza',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='Parvovirus',
        ),
        migrations.RemoveField(
            model_name='vaccination_card',
            name='rabies',
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='coronaviruz_1',
            field=models.BooleanField(default=False, verbose_name='coronaviruz_1'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='coronaviruz_2',
            field=models.BooleanField(default=False, verbose_name='coronaviruz_2'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='coronaviruz_3',
            field=models.BooleanField(default=False, verbose_name='coronaviruz_3'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='coronaviruz_4',
            field=models.BooleanField(default=False, verbose_name='coronaviruz_4'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='kennel_cough_1',
            field=models.BooleanField(default=False, verbose_name='kennel_cough_1'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='kennel_cough_2',
            field=models.BooleanField(default=False, verbose_name='kennel_cough_2'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='parvoviruz_1',
            field=models.BooleanField(default=False, verbose_name='parvoviruz_1'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='pentavalent_1',
            field=models.BooleanField(default=False, verbose_name='pentavalent_1'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='pentavalent_2',
            field=models.BooleanField(default=False, verbose_name='pentavalent_2'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='pentavalent_3',
            field=models.BooleanField(default=False, verbose_name='pentavalent_3'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='pentavalent_4',
            field=models.BooleanField(default=False, verbose_name='pentavalent_4'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='rabies_1',
            field=models.BooleanField(default=False, verbose_name='rabies_1'),
        ),
        migrations.AddField(
            model_name='vaccination_card',
            name='rabies_2',
            field=models.BooleanField(default=False, verbose_name='rabies_2'),
        ),
    ]
