# Generated by Django 4.2.4 on 2023-11-15 03:28

from django.db import migrations, models
import django.db.models.deletion
import vet.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_clinic_info_rating'),
        ('vet', '0038_remove_vaccination_card_adenovirus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(max_length=20)),
                ('date', models.DateField(validators=[vet.models.validate_minor])),
                ('vaccine_brand', models.CharField(max_length=20)),
                ('batch_number', models.IntegerField()),
                ('vaccination_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vet.vaccination_card')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vet')),
            ],
        ),
    ]
